database:
  user: hanko
  password: hanko
  host: postgresd
  port: 5432
  dialect: postgres
passcode:
  email:
    from_address: auth@knopoff.dev
  smtp:
    host: "mailslurper"
    port: "2500"
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Knopoff Authentication
webauthn:
  relying_party:
    origins:
    - "https://auth.knopoff.dev"
    - "https://recipes.knopoff.dev"
session:
  cookie:
    secure: true # is needed for safari, because safari does not store secure cookies on localhost
rate_limiter:
  enabled: true
  store: "redis"
  redis_config:
    address: "redis:6379"
password:
  enabled: true
server:
  cors:
    allow_origins:
      - "https://auth.knopoff.dev"
      - "https://recipes.knopoff.dev"
