services:
  hanko-migrate:
    build: ./backend
    command: --config ./config.yaml migrate up
    restart: on-failure
    depends_on:
      postgresd:
        condition: service_healthy
    networks:
      - intranet
  hanko:
    depends_on:
      hanko-migrate:
        condition: service_completed_successfully
    build: ./backend
    ports:
      - '8000:8000' # public
      - '8001:8001' # admin
    restart: unless-stopped
    command: serve --config ./config.yaml all
    networks:
      - intranet
    environment:
      - PASSWORD_ENABLED
  postgresd:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hanko
      - POSTGRES_PASSWORD=hanko
      - POSTGRES_DB=hanko
    healthcheck:
      test: pg_isready -U hanko -d hanko
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - intranet
  elements:
    build: ./frontend
    ports:
      - "9500:80"
    networks:
      - intranet
  quickstart:
    build: ./quickstart
    ports:
      - "8888:8080"
    environment:
      - HANKO_URL=https://auth.knopoff.dev
      - HANKO_URL_INTERNAL=http://hanko:8000
      - HANKO_ELEMENT_URL=https://auth-ui.knopoff.dev/elements.js
      - HANKO_FRONTEND_SDK_URL=https://auth-ui.knopoff.dev/sdk.umd.js
    networks:
      - intranet
  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '8080:8080' # web UI
      - '8085:8085'
    networks:
      - intranet
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - intranet
networks:
  intranet:
